#!/bin/bash

export NODE_ENV='dev'
export SPOTIFY_CLIENT_ID=967d0ee071fc41c99fcd12d6dc5718c0
export SPOTIFY_CLIENT_SECRET=caf7a40f87d342ac8735618a93b3a44d
export SPOTIFY_REDIRECT_URI=http://localhost:8080/auth-spotify/callback

export TICKETMASTER_KEY=MwOoif9Ac5iZFedZG7xMW368oRbghDAz
export TICKETMASTER_URL=https://app.ticketmaster.com/discovery/v2/

npm run start:dev
