require('bootstrap/dist/css/bootstrap.css')
require('bootstrap/dist/js/bootstrap.js')
require('./assets/styles.scss')
require('./assets/MesloLGMDZ-RegularForPowerline.ttf')
require('font-awesome/css/font-awesome.min.css')
require('./assets/imgs/bars.svg')
