module.exports = {
  "FOURSQ_CLIENT_ID":"Z50I5Y1CNTZTPIFFAY2WWUYCFNS5RYI4XTFIATDACTZKNOTL",
  "FOURSQ_CLIENT_SECRET":"S4WEDX3WRCCUT5ZHEPWBPD33HA0EIDORLIFIBYX42TOVK35O",
  "FOURSQ_API":"https://api.foursquare.com/v2/",
  "BASE_URI":"http://localhost:8888/"
}
